spring.application.name=demo

spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;DatabaseName=Bob;TrustServerCertificate=true;
spring.datasource.username=anton
spring.datasource.password=anton

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.mvc.hiddenmethod.filter.enabled=true

jwt.secret=bmVlZGVkU2VjdXJlS2V5MTIzNDU2Nzg5MGFiY2RlZmhpamtsbW5vcHFyc3RvdmVyZWplYmNkb3Juaw==
jwt.expiration=86400000
myCron=0 0 0 * * *